### PR TITLE
fix: do error on upload when a tag is not found anymore

### LINKED ISSUE #1211: [Bug]: workflow engine break upload when condition isn't met anymore
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a workflow need to tag a uploaded file and the tag is deleted, it blocks further uploads.

### Steps to reproduce

1. Create a tag `test`
2. Create a workflow to this tag `test` to uploads (for example all files smaller than 2 MB)
3. Delete tag `test`
4. Upload a new file: it's blocked because of missing tag

### Expected behavior

An invalid workflow shouldn't block upload or workflow should be deleted when tag is removed.

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by blizzz**
- als removes a listener to CacheEntryInsertedEvent since CacheEntryUpdatedEvent will be called as well
- logs a warning instead

fixes #1211 

Example log statements:

```json
{"reqId":"BXmsa5WqWcnyRe88EESb","level":2,"time":"2025-08-06T15:41:15+00:00","remoteAddr":"127.0.0.1","user":"spider","app":"files_automatedtagging","method":"PUT","url":"/remote.php/dav/files/spider/CanIHaz/error(2).jpeg","message":"The tag to assign (ID 77) cannot be found anymore. The related rule is owned by spider.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0","version":"32.0.0.1","data":{"app":"files_automatedtagging"}}

{"reqId":"BXmsa5WqWcnyRe88EESb","level":2,"time":"2025-08-06T15:41:16+00:00","remoteAddr":"127.0.0.1","user":"spider","app":"files_automatedtagging","method":"PUT","url":"/remote.php/dav/files/spider/CanIHaz/error(2).jpeg","message":"The tag to assign (ID 106) cannot be found anymore. The related rule is global.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0","version":"32.0.0.1","data":{"app":"files_automatedtagging"}}
```

Also comes with a little log spamming prevention, as the source events are apprently issued twice at least.

### CODE REVIEW

**Comment by blizzz** [comment]
> Because it could have security implication via access control I think breaking is better?

Good point. Still requires that a tag is being deleted pro-actively. Maybe an addition could be to check whether a tag is being used in a (accesscontrol) flow operation, when attempting to delete it. 

Both operations can be used in user as well as admin scope, might be hard to evaluate or even influence from an admin point of view.

File: lib/AppInfo/Application.php [hunk 1]
```diff
@@ -27,7 +26,6 @@ public function __construct() {
 
 	#[\Override]
 	public function register(IRegistrationContext $context): void {
-		$context->registerEventListener(CacheEntryInsertedEvent::class, CacheListener::class);
```
Comment (nickvergessen) [inline lib/AppInfo/Application.php]: Is this related?

**Review by nickvergessen — APPROVED** [review]
